ExpoBookApp/Controllers/EventController.cs
using ExpoBookApp.Migrations;
using ExpoBookApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System.Security.Claims;

namespace ExpoBookApp.Controllers
{
    public class EventController : Controller
    {
        private readonly AppDbContext _context;

        public EventController(AppDbContext context)
        {
            _context = context;
        }

        [Authorize]
        // GET: /Event/Index
        public IActionResult Index(string typeFilter = null)
        {
            var userEmail = User.Identity?.Name;
            var userRole = User.FindFirst(ClaimTypes.Role)?.Value;

            //Convert UTC to Malaysia Time Zone
            var malaysiaTimeZone = TimeZoneInfo.FindSystemTimeZoneById("Singapore Standard Time");
            var now = DateTime.UtcNow;


            if (string.IsNullOrEmpty(userEmail))
            {
                return Unauthorized();
            }

            var vm = new EventIndexViewModel();

            // Only show events created by the organizer
            vm.CreatedEvents = _context.Events
                .Include(e => e.CreatedBy)
                .Where(e => e.CreatedBy.Email == userEmail && !e.IsCancelled)
                .ToList();

            vm.DeletedEvents = _context.Events
                .Include(e => e.CreatedBy)
                .Where(e => e.CreatedBy.Email == userEmail && e.IsCancelled)
                .ToList();

            // Only show upcomming events created by the organizer
            vm.CreatedUpcomingEvents = _context.Events
                .Include(e => e.CreatedBy)
                .Where(e => e.CreatedBy.Email == userEmail && e.StartDate > now && !e.IsCancelled)
                .OrderBy(e => e.StartDate)
                .ToList();
            
            // List of upcoming events
            vm.UpcomingEvents = _context.Events
                .Include(e => e.CreatedBy)
                .Where(e => e.StartDate > now && !e.IsCancelled)
                .OrderBy(e => e.StartDate)
                .Take(5)
                .ToList();

            // List of all events (optionally filtered by theme)
            var allEventsQuery = _context.Events.AsQueryable();

            if (!string.IsNullOrEmpty(typeFilter))
            {
                allEventsQuery = allEventsQuery
                    .Where(e => e.EventType == typeFilter && !e.IsCancelled);
            }
            vm.AllEvents = allEventsQuery
                .Include(e => e.CreatedBy)
                .ToList();

            // Event Type for dropdown filter
            vm.EventType = _context.Events
                .Include(e => e.CreatedBy)
                .Where(e => !e.IsCancelled)
                .Select(e => e.EventType)
                .Distinct()
                .ToList();

            vm.TypeFilter = typeFilter;

            return View(vm);
        }

        //GET: /Event/Explore
        [Authorize(Roles = "Participants")]
        public IActionResult Explore(string search, DateTime? startDate, DateTime? endDate)
        {
            // Check if user is authenticated

            var userEmail = User.Identity.Name;
            var user = _context.Users.FirstOrDefault(u => u.Email == userEmail);

            if (user == null)
                return Unauthorized();

            var events = _context.Events
                .Include(e => e.CreatedBy)
                .Where(e => e.StartDate >= DateTime.UtcNow && !e.IsCancelled);

            if (!string.IsNullOrEmpty(search))
            {
                events = events.Where(e =>
                    e.EventName.Contains(search) ||
                    e.Description.Contains(search));
            }

            if (startDate.HasValue)
            {
                events = events.Where(e => e.StartDate >= startDate.Value);
            }
            if (endDate.HasValue)
            {
                events = events.Where(e => e.EndDate <= endDate.Value);
            }

            var eventList = events.OrderBy(e => e.StartDate)
                .ToList();

            return View(eventList);
        }

        // GET: /Event/Detail/5
        public async Task<IActionResult> Detail(int? id)
        {
            if (id == null)
                return NotFound();

            var @event = await _context.Events.FirstOrDefaultAsync(e => e.Id == id);
            if (@event == null)
                return NotFound();

            return View(@event);
        }

        [Authorize]
        // GET: /Event/Create
        public IActionResult Create()
        {
            ViewBag.Venues = _context.Venues
                .Include(v => v.CreatedBy)
                .Where(v => v.ApprovalStatus == ApprovalStatus.Approved && v.IsActive)
                .ToList();

            return View();
        }

        // POST: /Event/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Event @event, IFormFile ImageFile)
        {
            ModelState.Remove("ImageFile");

            if (ModelState.IsValid)
            {
                var userEmail = User.Identity.Name; // assuming email is stored in cookie
                var user = _context.Users.FirstOrDefault(u => u.Email == userEmail);
                if (user == null) return Unauthorized();

                var today = DateTime.UtcNow;

                @event.CreatedByUserId = user.Id; // Set the creator of the event

                //Check if the event name is already taken
                if (_context.Events.Any(e => e.EventName == @event.EventName && e.CreatedByUserId == user.Id))
                {
                    ModelState.AddModelError("EventName", "An event with this name already exists.");
                    return View(@event);
                }

                //Date validation
                //Check if end date is not before start date
                if (@event.EndDate < @event.StartDate)
                {
                    ModelState.AddModelError("EndDate", "End date must be after the start date.");
                    return View(@event);
                }

                //Check if the event is in the past
                if (@event.StartDate < today)
                {
                    ModelState.AddModelError("StartDate", "Start date must be after today.");
                    return View(@event);
                }

                //Free event to mark as public event
                if (@event.TicketPrice == 0 && @event.TicketQuota > 0)
                {
                    @event.IsPublic = true;
                }

                if (@event.Venue == "Online")
                {
                    @event.IsOnline = true;
                }
                else
                {
                    @event.IsOnline = false;
                }

                ////Image check and save
                //if (ImageFile != null && ImageFile.Length > 0)
                //{
                //    var uploadsFolder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images");
                //    if (!Directory.Exists(uploadsFolder))
                //        Directory.CreateDirectory(uploadsFolder);

                //    var uniqueFileName = Guid.NewGuid().ToString() + Path.GetExtension(ImageFile.FileName);
                //    var filePath = Path.Combine(uploadsFolder, uniqueFileName);

                //    using (var stream = new FileStream(filePath, FileMode.Create))
                //    {
                //        await ImageFile.CopyToAsync(stream);
                //    }

                //    @event.ImagePath = "/images/" + uniqueFileName;
                //}

                _context.Add(@event);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ViewBag.Venues = _context.Venues
                .Where(v => v.ApprovalStatus == ApprovalStatus.Approved && v.IsActive)
                .ToList();

                return View(@event);
            }
        }

        [Authorize]
        // GET: /Event/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            var @event = await _context.Events.FindAsync(id);
            if (@event == null)
                return NotFound();

            return View(@event);
        }

        // POST: /Event/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Event @event)
        {
            var userEmail = User.Identity.Name; // assuming email is stored in cookie
            var user = _context.Users.FirstOrDefault(u => u.Email == userEmail);
            if (user == null) return Unauthorized();

            var today = DateTime.UtcNow;

            @event.CreatedByUserId = user.Id;

            //Check if the event name is already taken
            if (_context.Events.Any(e => 
                                    e.EventName == @event.EventName && 
                                    e.CreatedByUserId == user.Id &&
                                    e.Id != @event.Id))
            {
                ModelState.AddModelError("EventName", "An event with this name already exists.");
                return View(@event);
            }

            //Date validation
            if (@event.EndDate < @event.StartDate)
            {
                ModelState.AddModelError("EndDate", "End date must be after the start date.");
                return View(@event);
            }
            if (@event.StartDate < today)
            {
                ModelState.AddModelError("StartDate", "Start date must be after today.");
                return View(@event);
            }


            if (id != @event.Id)
                return NotFound();

            if (ModelState.IsValid)
            {

ExpoBookApp/Controllers/VenueController.cs
using ExpoBookApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace ExpoBookApp.Controllers
{
    public class VenueController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;

        public VenueController(AppDbContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            _hostEnvironment = hostEnvironment;
        }

        [Authorize(Roles = "Leaser")]
        [HttpGet]
        public IActionResult Index()
        {
            var userEmail = User.Identity.Name;
            var userRole = User.FindFirst(ClaimTypes.Role)?.Value;

            var venues = _context.Venues
                .Include(v => v.CreatedBy)
                .Where(v => v.CreatedBy.Email == userEmail && v.IsActive)
                .ToList();
            return View(venues);
        }

        [Authorize(Roles = "Leaser")]
        [HttpGet]
        // GET: Venue/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Venue/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Venues venue/*, IFormFile SupportDoc*/)
        { 
            var user = _context.Users.FirstOrDefault(u => u.Email == User.Identity.Name);
            if (user == null) return Unauthorized();

            venue.CreatedByUserId = user.Id;
            venue.CreatedAt = DateTime.UtcNow;
            venue.ApprovalStatus = ApprovalStatus.Pending;
            venue.SupportingDocumentPath = "n/a"; // Default value, Placeholder to be updated

            if (ModelState.IsValid)
            {
                ////Supporting document upload
                //if (SupportDoc != null && SupportDoc.Length > 0)
                //{
                //    var uploadsFolder = Path.Combine(_hostEnvironment.WebRootPath, "uploads", "supporting-documents");
                //    if (!Directory.Exists(uploadsFolder))
                //        Directory.CreateDirectory(uploadsFolder);

                //    var fileName = $"{Guid.NewGuid()}_{Path.GetFileName(SupportDoc.FileName)}";
                //    var filePath = Path.Combine(uploadsFolder, fileName);

                //    using (var stream = new FileStream(filePath, FileMode.Create))
                //    {
                //        await SupportDoc.CopyToAsync(stream);
                //    }

                //    venue.SupportingDocumentPath = "/uplaods/" +  fileName;
                //}

                _context.Add(venue);
                await _context.SaveChangesAsync();

                TempData["SuccessMessage"] = "Venue created successfully and is pending approval.";
                return RedirectToAction(nameof(Index));
            }
            return View(venue);
        }

        // GET: Venue/Edit
        [Authorize(Roles = "Leaser")]
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            var @venue = await _context.Venues.FindAsync(id);
            if (@venue == null)
                return NotFound();

            return View(@venue);
        }

        // POST: Venue/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Venues venue)
        {
            var userEmail = User.Identity.Name; // assuming email is stored in cookie
            var user = _context.Users.FirstOrDefault(u => u.Email == userEmail);
            if (id != venue.Id)
                return NotFound();

            // Check if the venue name is already taken by another venue created by the same user
            if (_context.Venues.Any(v =>
                                    v.Name == venue.Name &&
                                    v.CreatedByUserId == user.Id &&
                                    v.Id != venue.Id))
            {
                ModelState.AddModelError("Name", "Venue name already exists for another venue created by you.");
                return View(venue);
            }

            //Maintain CreatedByUserId to original user
            if (user == null)
                return Unauthorized();
            venue.CreatedByUserId = user.Id; 

            //Maintain CreatedAt value to original
            venue.CreatedAt = _context.Venues.AsNoTracking().FirstOrDefault(v => v.Id == id)?.CreatedAt ?? DateTime.UtcNow;
            venue.SupportingDocumentPath = "n/a";

            venue.ApprovalStatus = ApprovalStatus.Pending; //Set status to pending when editing to be approved again

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(venue);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_context.Venues.Any(v => v.Id == id))
                        return NotFound();
                    else
                        throw;
                }
                return RedirectToAction(nameof(Index));
            }

            return View(venue);
        }

        // GET: Venue/Detail
        [Authorize(Roles = "Leaser")]
        public async Task<IActionResult> Detail(int? id)
        {
            if (id == null)
                return NotFound();

            var venue = await _context.Venues
                .FirstOrDefaultAsync(m => m.Id == id);

            if (venue == null)
                return NotFound();

            return View(venue);
        }

        // GET: Venue/Delete
        [Authorize(Roles = "Leaser")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var venue = await _context.Venues
                .Include(v => v.CreatedBy)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (venue == null)
                return NotFound();

            var hasUpcomingEvents = _context.Events
                .Any(e => e.Venue == venue.Name && e.EndDate >= DateTime.UtcNow && !e.IsCancelled);

            ViewBag.HasUpcomingEvents = hasUpcomingEvents;

            return View(venue);
        }

        // POST: Venue/Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var venue = await _context.Venues.FindAsync(id);
            var affectedEvents = _context.Events
                .Where(e => e.Venue == venue.Name && e.EndDate >= DateTime.UtcNow && !e.IsCancelled)
                .ToList();

            if (venue != null)
            {
                venue.IsActive = false;
                affectedEvents.ForEach(e => e.IsCancelled = true);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

ExpoBookApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
@{
        var role = User.FindFirst(System.Security.Claims.ClaimTypes.Role)?.Value;
}
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExpoBookApp</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ExpoBookApp.styles.css" asp-append-version="true" />
    <link href="https://fonts.googleapis.com/css2?family=Silkscreen:wght@400;700&display=swap" rel="stylesheet" />
</head>

<body>
    <!-- Flex container wrapper -->
    <div class="d-flex flex-column min-vh-100">
        <header>
            <nav class="navbar nav-pills navbar-expand-sm navbar-toggleable-sm navbar-light bg-warning border-bottom box-shadow mb-3">
                <div class="container-fluid">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="font-family:silkscreen; font-weight:bold">EXPO-BOOK-APP</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            @if (role == "Organizer")
                            {
                                <li class="nav-item"><a class="nav-link text-dark" asp-controller="Event" asp-action="Index">Browse Event</a></li>
                                <li><a class="nav-link text-dark" asp-controller="Event" asp-action="Create">Create Event</a></li>
                            }
                            else if (role == "Leaser")
                            {
                                <li class="nav-item"><a class="nav-link text-dark" asp-controller="Venue" asp-action="Index">Venue</a></li>
                                <li><a class="nav-link text-dark" asp-controller="Venue" asp-action="Create">List New Venue</a></li>
                            }
                            else if (role == "Participants")
                            {
                                <li class="nav-item"><a class="nav-link text-dark" asp-controller="Event" asp-action="Explore">Browse Event</a></li>
                                <li class="nav-item"><a class="nav-link text-dark" asp-controller="Ticket" asp-action="MyTickets">My Ticket</a></li>
                            }
                            else if (role == "Admin")
                            {
                                <li class="nav-item"><a class="nav-link text-dark" asp-controller="Admin" asp-action="#">Dashboard</a></li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" role="button">Leaser</a>
                                    <ul class="dropdown-menu">
                                        <li><a class="dropdown-item" asp-controller="Admin" asp-action="PendingVenues">Listing Approval</a></li>
                                    </ul>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item"><a class="nav-link text-dark" asp-controller="Home" asp-action="BrowseEvent">Available Event</a></li>
                            }
                        </ul>
                        <ul class="navbar-nav ms-auto">
                            @if (User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item"><span class="navbar-text me-2">Hello, @User.Identity.Name!</span></li>
                                <li class="nav-item"><a class="btn btn-outline-danger btn-sm" asp-controller="Account" asp-action="Logout">Logout</a></li>
                            }
                            else
                            {
                            @* <li class="dropstart">
                                <button class="btn btn-primary dropdown-toggle show" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                                    Login
                                </button>
                                <ul class="dropdown-menu show" style="position: absolute; inset: 0px 0px auto auto; margin: 0px; transform: translate(-158.625px, 0px);" data-popper-placement="left-start">
                                    <form asp-controller="Account" asp-action="Login" class="mx-auto">
                                        <div class="form-group">
                                            <label for="exampleDropdownFormEmail1">Email address</label>
                                            <input type="email" class="form-control" id="exampleDropdownFormEmail1" placeholder="email@example.com">
                                        </div>
                                        <div class="form-group">
                                            <label for="exampleDropdownFormPassword1">Password</label>
                                            <input type="password" class="form-control" id="exampleDropdownFormPassword1" placeholder="Password">
                                        </div>
                                        <button type="submit" class="btn btn-primary">Log in</button>
                                    </form>
                                    <div class="dropdown-divider"></div>
                                    <div>
                                        <p>New around here? </p><a asp-controller="Account" asp-action="Register" class="dropdown-item">Register Here!</a>
                                    </div>
                                    <div>
                                        <a asp-controller="Account" asp-action="Forgot Password" class="dropdown-item">Forgot password?</a>
                                    </div>
                                </ul>
                            </li> *@
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                            }
                        </ul>
                    </div>
                </div>
            </nav>
        </header>

        <main class="flex-grow-1">
            <div class="container py-4">
                @RenderBody()
            </div>
        </main>

        <footer class="text-muted py-3 border-top mt-auto">
            <div class="container text-center">
                &copy; 2025 - ExpoBookApp - <a asp-controller="Home" asp-action="ContactUs">Contact Us</a>
            </div>
        </footer>
    </div>

    <!-- Scripts -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.5/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>